sudo: false

language: node_js

node_js:
  - stable

cache:
  yarn: true
  directories:
  - node_modules

before_install: export TZ=UTC

install: yarn

script:
  - yarn run lint
  - yarn test -- --coverage

after_success: yarn run coveralls
